<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8" %>
<script type="text/javascript">
    var _menus = {"menus":[
        {"menuid":"1","icon":"icon-sys","menuname":"订单管理",
            "menus":[
                {"menuid":"12","menuname":"订单管理","icon":"icon-add","url":"${ctx}/order/index"},
                {"menuid":"13","menuname":"用户管理","icon":"icon-users","url":"a.html"},
                {"menuid":"14","menuname":"角色管理","icon":"icon-role","url":"http://www.baidu.com"},
                {"menuid":"15","menuname":"权限设置","icon":"icon-set","url":"demo.html"},
                {"menuid":"16","menuname":"系统日志","icon":"icon-log","url":"demo1.html"}
            ]
        },
        {"menuid":"8","icon":"icon-sys","menuname":"库存管理",
            "menus":[
                {"menuid":"21","menuname":"合同出库","icon":"icon-nav","url":"${ctx}/stock/index"},
                {"menuid":"22","menuname":"其他出库","icon":"icon-nav","url":"${ctx}/stock/otherOut"},
                {"menuid":"22","menuname":"出库订单","icon":"icon-nav","url":"${ctx}/stock/outOrder"},
                {"menuid":"22","menuname":"采购申请","icon":"icon-nav","url":"${ctx}/stock/apply"}
            ]
        },
        {"menuid":"56","icon":"icon-sys","menuname":"部门管理",
            "menus":[{"menuid":"31","menuname":"添加部门","icon":"icon-nav","url":"demo1.html"},
                {"menuid":"32","menuname":"部门列表","icon":"icon-nav","url":"demo2.html"}
            ]
        },
        {"menuid":"28","icon":"icon-sys","menuname":"财务管理",
            "menus":[{"menuid":"41","menuname":"收支分类","icon":"icon-nav","url":"demo.html"},
                {"menuid":"42","menuname":"报表统计","icon":"icon-nav","url":"demo1.html"},
                {"menuid":"43","menuname":"添加支出","icon":"icon-nav","url":"demo2.html"}
            ]
        },
        {"menuid":"39","icon":"icon-sys","menuname":"商城管理",
            "menus":[{"menuid":"51","menuname":"商品分类","icon":"icon-nav","url":"demo.html"},
                {"menuid":"52","menuname":"商品列表","icon":"icon-nav","url":"demo1.html"},
                {"menuid":"53","menuname":"商品订单","icon":"icon-nav","url":"demo2.html"}
            ]
        }
    ]};
</script>